### ISSUE TITLE
Add support for text selection on mobile

### ISSUE THREAD

**Issue by suhaotian** [zenorocha/clipboard.js#26] opened 2015-09-30 09:07 UTC

**Comment by enociz** [comment] 2015-09-30 09:32
```
Not supported :(
```

I would really like to see it in mobile because a lot of _other_ options don't do it.

**Comment by chrismanderson** [comment] 2015-09-30 13:53
For clarity, when I tested on both Safari and Chrome mobile browsers on iOS when, when I click a copy button on the demo site, I just see the 'Not Supported' popup. The browser focuses the input field, but the text is not selected. Even if we can't copy directly to clipboard on mobile, are there browser APIs available to at least automatically select the text waiting to be copied?

**Comment by enociz** [comment] 2015-09-30 23:15
@chrismanderson I did the exact same thing and got the exact same results.

**Comment by zenorocha** [comment] 2015-09-30 23:44
As described in the [Browser Support section](https://github.com/zenorocha/clipboard.js#browser-support), [execCommand](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand) is not supported on mobile yet. So for now, there's nothing we can do about it.

Regarding text selection on mobile, there's seems to be a workaround using `setSelectionRange` http://stackoverflow.com/questions/3272089/programmatically-selecting-text-in-an-input-field-on-ios-devices-mobile-safari

Pull requests are welcome.

**Comment by mdibaiee** [comment] 2015-10-01 13:30
@zenorocha: I'm interested in fixing this bug, may you please clarify what exactly should be done?

Are we going to select the input text only if we're on mobile and copy is not supported?

**Comment by zenorocha** [comment] 2015-10-01 15:40
What should be done is simply selecting text on mobile devices.

**Comment by ryanpcmcquen** [comment] 2015-10-09 21:06
I do this (copies on desktop and Android, and selects on iOS): https://jsfiddle.net/ryanpcmcquen/dx5vvzc1/

**Comment by zenorocha** [comment] 2015-10-09 21:25
Hey @ryanpcmcquen, I tested on an iPhone & iPad but selection didn't work.

**Comment by ryanpcmcquen** [comment] 2015-10-09 21:29
@zenorocha are you on iOS 9? Try the full screen version. Works here for me.

![screen shot 2015-10-09 at 2 28 35 pm](https://cloud.githubusercontent.com/assets/772937/10406046/20364996-6e92-11e5-8ac2-ace63efe8eff.png)

**Comment by zenorocha** [comment] 2015-10-09 21:32
Confirmed that it does work on the iOS simulator but not on real devices.

**Comment by ryanpcmcquen** [comment] 2015-10-09 21:35
:anguished:

**Comment by axelman24** [comment] 2015-10-09 22:14
I just tested this on my iphone and my ipad and it worked for me! (Tested it in Safari)

**Comment by axelman24** [comment] 2015-10-09 22:15
@zenorocha @ryanpcmcquen See comment above.

**Comment by ryanpcmcquen** [comment] 2015-10-09 23:02
Since it does seem to work on some iOS devices, I implemented a library for it:

https://github.com/ryanpcmcquen/simpleJsCopy

Not as robust as clipboard.js, but it may suit some people's needs. :+1:

**Comment by zenorocha** [comment] 2015-10-15 23:34
Hey @ryanpcmcquen,

I see you [discovered](https://github.com/ryanpcmcquen/simpleJsCopy/blob/gh-pages/simpleJsCopy.js#L32-L34) how make a selection on iOS devices.

Could you make a PR?

**Comment by ryanpcmcquen** [comment] 2015-10-16 13:53
@zenorocha, I see you could not be bothered to star my repo while asking for code from it ... :confused:

**Comment by zenorocha** [comment] 2015-10-19 23:23
Hey everyone, I just moved all selection logics from clipboard.js to a different repo called [select](https://github.com/zenorocha/select) https://github.com/zenorocha/clipboard.js/commit/c6dc01cc298dd9793ad81eb4e159128913d74469.

Also moving this issue there https://github.com/zenorocha/select/issues/1

**Closed by zenorocha** 2015-10-19 23:23 UTC
Labels: help wanted, improvement, p1
