### ISSUE TITLE
Page hangs after copy the text

### ISSUE THREAD

**Issue by rixcapricorn** [zenorocha/clipboard.js#869] opened 2024-01-09 15:37 UTC
I have used copy to clipboard in my page to copy some token. But after copying the text, after few seconds, page gets hang, modal pop up is automatically gone + toggle switch is lost (see in background page, enable/disable token toggle button), javascript events lost.

**Comment by obetomuniz** [comment] 2024-06-20 02:44
Hey @rixcapricorn, thanks for reporting, I'm planning to contribute to some open issues. Can you confirm if your problem remains? For now, without a proposal demo to reproduce, I am closing the report since it seems a not related clipboard.js bug to me. You are welcome to re-open if including a reproducible demo using jsfiddle or something like that.

**Closed as completed by obetomuniz** 2024-06-20 02:44 UTC
Labels: bug
