### ISSUE TITLE
when the content contains '\n' or '\r' ,how to write the string?

### ISSUE THREAD

**Issue by jerryniepan** [zenorocha/clipboard.js#450] opened 2017-07-21 10:46 UTC
### Minimal example

> Fork this [JSFiddle](https://jsfiddle.net/zenorocha/5kk0eysw/) and reproduce your issue.

### Expected behaviour

I thought that by going to the page '...' and pressing the button '...' then '...' would happen.

### Actual behaviour

Instead of '...', what I saw was that '...' happened instead.

### Browsers affected

I tested on all major browsers and only IE 11 does not work.

**Comment by Smile4ever** [comment] 2017-08-13 17:46
Use a textarea?
<textarea id="foo" type="text" value="hello"></textarea>

**Comment by Ruffio** [comment] 2018-03-01 22:29
@jerryniepan what is the issue? Can you supply a code sample demonstrating the issue?

**Comment by zenorocha** [comment] 2018-03-01 22:32
Closing since no information has been provided on how to reproduce it.

**Closed by zenorocha** 2018-03-01 22:32 UTC
