### ISSUE TITLE
Copy call back got text but not on clipboard???

### ISSUE THREAD

**Issue by jinfagang** [zenorocha/clipboard.js#542] opened 2018-04-23 11:38 UTC
Very strange bug. I can log text, not on clipboard.
```
 var clipboard = new ClipboardJS('#copyCodeBtn').on('success', function(e) {
                var e = e || window.event;
                console.log(e);
                alert('邀请推广复制成功，粘贴至微信即可邀请好友加入，复制内容：\n' + e.text);
            }).on('error', function(e) {
                console.log('fucking copy error');
                alert('复制出现错误，请手动复制邀请码分享');
                console.log(e)
            });
```

Html:
```
 <textarea id="copyContent">快来加入仙推广联盟，点击链接注册账号，即刻拥有自己的电子商城！{{my_invite_url}}</textarea>
        <div>
            <button class="fd-btn-gradient-green" style="margin-top: 20px" @click="actionEditFile">资料修改通道</button>
            <button id="copyCodeBtn" class="fd-btn-gradient-green" style="margin-top: 20px" @click="actionShareCode"
                    data-clipboard-action="copy" data-clipboard-target="#copyContent">分享邀请码</button>
        </div>
```

**Comment by kayandrae07** [comment] 2018-04-25 10:54
Sorry, but I couldn't reproduce. I also tried with Hiragana, Kanji, Katakana and Cyrillic and it works fine. Here's a working demo https://codepen.io/anon/pen/GdqWBR?editors=1010

**Comment by zenorocha** [comment] 2018-04-29 22:58
Closing since we weren't able to reproduce.

Thanks a lot @kayandrae07!!!

**Closed by zenorocha** 2018-04-29 22:58 UTC

**Comment by ngelx** [comment] 2018-07-12 15:41
For future references. If this happen in an element that change focus (i.e. Bootstrap modals)
check the [doc -> Adance usange](https://clipboardjs.com/#advanced-usage). It can be fixed setting the `container` value

**Comment by yangkennyk** [comment] 2019-01-30 17:16
> For future references. If this happen in an element that change focus (i.e. Bootstrap modals)
> check the [doc -> Advance usange](https://clipboardjs.com/#advanced-usage). It can be fixed setting the `container` value

the the real MVP
