### ISSUE TITLE
Clipboard is undefined in IE9,11

### ISSUE THREAD

**Issue by brunce2** [zenorocha/clipboard.js#214] opened 2016-03-30 06:33 UTC
it happens "Clipboard is undefined" error, 
see the following picture.

![untitled](https://cloud.githubusercontent.com/assets/10023506/14133968/0d01a146-f686-11e5-8578-757ebee0b6c1.png)

this page is developed  in vs2010,and it is included iframe. 
i think it is not a issue,Perhaps I don't know deeply for clipboard.
someone else has encountered this issue before?

**Comment by kafeltz** [comment] 2016-03-30 11:59
How did you create your object?

**Comment by zenorocha** [comment] 2016-03-30 15:25
Closing issue since it didn't follow the [issue template](https://github.com/zenorocha/clipboard.js/blob/master/.github/issue_template.md). Please share a JSFiddle in order for us to reproduce the problem.

**Closed by zenorocha** 2016-03-30 15:25 UTC

**Comment by brucejcw** [comment] 2016-11-03 04:42
@zenorocha [official demo](https://clipboardjs.com/) not work on ie9  
![2016-11-03 12 41 15](https://cloud.githubusercontent.com/assets/8085088/19956064/dbb1e630-a1c2-11e6-87fa-dd2b398ddee8.png)
