### ISSUE TITLE
copyFromContent is not working on Safari (Mac OS)

### ISSUE THREAD

**Issue by lucasvalentee** [zenorocha/clipboard.js#822] opened 2022-10-10 19:30 UTC
Hello guys. I use the lib in Angular (14+) and I have a method to copy a text from the screen, but it's not working in Safari browser when using Mac OS.

I tested it on my IOS phone and on Chrome and Mozilla browsers too (desktop), in both the method I copied the text correctly.

I did some research and testing in Safari and apparently the browser doesn't have much support for copying content to the clipboard.

Does anyone know if there is a solution to this problem?

`async generateAndCopyLink() {
    const shortUrl = await this.shortenerService.getShortUrl(exampleUrl);
    this.clipboardService.copyFromContent(shortUrl);
}`

**Comment by obetomuniz** [comment] 2022-10-13 22:14
Hi @lucasvalentee, for this scenario, it is important to share a demo to reproduce the issue. Without that, we can't help you connect the library with Angular as you need.

The vanilla library is working with Safari/MacOS. Closing for now since it seems not related to the library. Feel free to reopen when you have the demo.

**Closed by obetomuniz** 2022-10-13 22:14 UTC
Labels: bug
