### ISSUE TITLE
hidden

### ISSUE THREAD

**Issue by Theolodewijk** [zenorocha/clipboard.js#608] opened 2018-12-15 14:24 UTC
kopie hidden element not work, how to bypass?

<span class="input-group-button"><button class="btn clipboard_button" type="button" data-clipboard-target="#image-' . $i . '"><i class="fas fa-clipboard-list"></i></button>&nbsp;</span>
						<input type="hidden" class="form-control" data-placement="bottom" id="image-' . $i . '" value="' . $url . '">

**Comment by bernd-wechner** [comment] 2019-02-04 11:59
Duplicate of https://github.com/zenorocha/clipboard.js/issues/560
Suggest closing this.

**Comment by zenorocha** [comment] 2020-02-29 19:47
Thanks @bernd-wechner!

**Closed** 2020-02-29 19:47 UTC
