### ISSUE TITLE
Plug-in elements to prevent bubbling failure, I hope the author can fix this problem, thank you.

### ISSUE THREAD

**Issue by lvleihere** [zenorocha/clipboard.js#520] opened 2018-01-31 07:51 UTC
### Minimal example

> Fork this [JSFiddle](https://jsfiddle.net/zenorocha/5kk0eysw/) and reproduce your issue.

### Expected behaviour

I thought that by going to the page '...' and pressing the button '...' then '...' would happen.

### Actual behaviour

Instead of '...', what I saw was that '...' happened instead.

### Browsers affected

I tested on all major browsers and only IE 11 does not work.

**Comment by lvleihere** [comment] 2018-01-31 07:52
Plug-in elements to prevent bubbling failure, I hope the author can fix this problem, thank you.

**Comment by Ruffio** [comment] 2018-03-01 22:22
What is the issue? Please provide a simple sample.

**Comment by zenorocha** [comment] 2018-03-01 22:31
Closing since no information has been provided on how to reproduce it.

**Closed by zenorocha** 2018-03-01 22:31 UTC
