### ISSUE TITLE
When it is used with bootstrap model it jumps at the top of the page on IE 11 

### ISSUE THREAD

**Issue by baris22** [zenorocha/clipboard.js#526] opened 2018-02-10 23:32 UTC
I am trying to copy from the modal window.
If I call it as:
`var clipboard = new Clipboard('.copy-button');`
 it causes problem with Chrome, I can see the copied text in the console but it is not available when I paste it. so I changed it to:
```
var clipboard = new Clipboard('.copy-button', {
	container: document.getElementById('exampleModalLong')
});
```
Now I am having a problem with IE 11. When I press the copy button, it jumps to the top of the page.

**Comment by zenorocha** [comment] 2018-04-29 23:13
Closing since a minimal example that reproduces the error has not been provided.

**Closed by zenorocha** 2018-04-29 23:13 UTC
