### ISSUE TITLE
Packaging issue with Clipboard v2?

### ISSUE THREAD

**Issue by jasonroelofs** [zenorocha/clipboard.js#535] opened 2018-03-14 14:34 UTC
### Minimal example

Not sure how to show this via JSFiddle, but `dist/clipboard.js` is missing the `clipboard-action.js` module. The file `dist/clipboard.min.js` does correctly contain the module.

### Expected behaviour

Compilation succeeds with no issue.

### Actual behaviour

Compilation error when building my javascript, which uses the unminified `dist/clipboard.js`:

```
BrowserifyRails::BrowserifyError: Error while running `...`:
events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: Cannot find module './clipboard-action' from '...'
```

**Comment by Ruffio** [comment] 2018-04-03 07:59
@jasonroelofs is this still an issue? How about making an PR for it?

**Comment by marnen** [comment] 2018-04-04 21:11
Still an issue:
```
error: Processing of node_modules/clipboard/dist/clipboard.js failed. Error: Could not load module './clipboard-action' from '/Users/marnen/Documents/kostakowsky/node_modules/clipboard/dist'. Make sure the file actually exists.
```

**Comment by marnen** [comment] 2018-04-05 05:46
@matthewmcvickar Yeah, that's what I did. It's still annoying. :)

**Comment by allenfantasy** [comment] 2018-04-27 10:10
I met some similar problems when using it with an Angular2 project:

```js
import ClipboardJS from 'clipboard'
// or:
import ClipboardJS from 'clipboard/dist/clipboard'
// or: 
import ClipboardJS from 'clipboard/dist/clipboard.min'
```
would cause a `Cannot find module 'clipboard` error.

**Comment by matthewmcvickar** [comment] 2018-04-27 22:39
@allenfantasy Have you tried `import ClipboardJS from 'clipboard/dist/clipboard.min.js'`?

**Comment by allenfantasy** [comment] 2018-04-28 13:11
@matthewmcvickar I just tried your way both, unfortunately none of them works.

I am not sure it has something to do with Webpack config - since Angular2 wrap the webpack configurations into a blackbox it's not easy to debug via it.

I would try to import Clipboard in a bare simple Webpack project to see if it works.

**Comment by allenfantasy** [comment] 2018-04-28 13:39
Okay. I've tried it in a bare Webpack2 project (using `webpack@2.4.x` which is the same with the webpack version used in my Angular2 project) : https://stackblitz.com/edit/clipboard-webpack2

Actually I tried it first in my local laptop when I move it to Stackblitz - both works except that I could directly import Clipboard in local but have to import `clipboard/dist/clipboard.min` in Stackblitz (don't know why)

**Comment by zenorocha** [comment] 2018-04-29 23:43
This should be fixed on v2.0.1. Let me know if you're still facing any problems.

**Closed by zenorocha** 2018-04-29 23:43 UTC

**Comment by lsg-richard** [comment] 2018-04-30 22:49
Still seeing this on 2.0.1 unfortunately.

I'm importing the `clipboard` package into my Ember 3.1 application using:

    import ClipboardJS from 'npm:clipboard/dist/clipboard.min'

And changing this to

    import ClipboardJS from 'npm:clipboard'

which is the import style we use for all other NPM packages causes the following error:

    Cannot find module './clipboard-action' from '/home/richard/code/wavelength/node_modules/clipboard/dist'

This is on clipboard.js 2.0.1, ember-cli 3.1.2, ember-browserify 1.2.2. Don't think this issue is specific to Ember projects though.

**Comment by zenorocha** [comment] 2018-05-28 23:51
I couldn't reproduce this error. When I use webpack + babel it imports correctly. Could you share a minimal reproducible example?

**Comment by YanivKimhi** [comment] 2018-05-30 10:27
# package.json
{
  "scripts": {
    "browserify-test": "browserify ./test.jsx -o test.js"
  },
  "browserify": {
    "transform": [
      "babelify"
    ]
  },
  "dependencies": {
    "babelify": "6.1.3",
    "browserify": "16.2.2",
    "clipboard": "^2.0.1",
  }
}

# test.jsx:
import Clipboard from 'clipboard';

# Run
npm run browserify-test

# Result: 
Error: Cannot find module './clipboard-action' from '... .../node_modules/clipboard/dist'
