### ISSUE TITLE
clipboard did not run for the first click . It only runs with double click in the first times

### ISSUE THREAD

**Issue by toolaugh** [zenorocha/clipboard.js#463] opened 2017-08-26 06:56 UTC
### Minimal example

> Fork this [JSFiddle](https://jsfiddle.net/zenorocha/5kk0eysw/) and reproduce your issue.

### Expected behaviour

I thought that by going to the page '...' and pressing the button '...' then '...' would happen.

### Actual behaviour

Instead of '...', what I saw was that '...' happened instead.

### Browsers affected

I tested on all major browsers and only IE 11 does not work.

**Comment by tprupsys** [comment] 2017-08-31 08:53
same here

**Comment by Ruffio** [comment] 2017-09-17 09:44
What is the issue? I can't reproduce your issue with your JSFiddler provided...

**Comment by flexbox** [comment] 2017-12-08 10:49
Hello @toolaugh 
Any update on this?
If the problem is solved you can close the issue 😉

**Comment by springxiege** [comment] 2018-03-01 09:33
I have the same problem , have you resolved it ?

**Comment by Ruffio** [comment] 2018-04-03 07:54
@toolaugh what is th issue here? Can you provide an example in JSBin or similar? Else please close this issue.

**Comment by zenorocha** [comment] 2018-04-29 23:40
Closing since an example has not been provided.

**Closed by zenorocha** 2018-04-29 23:40 UTC
