### ISSUE TITLE
[question] when use `clipboard.destroy()` in vue methods,clipboard does not work

### ISSUE THREAD

**Issue by KeepChen** [zenorocha/clipboard.js#486] opened 2017-10-20 02:50 UTC
##when use `clipboard.destroy()` does not work
import Clipboard from 'clipboard';
  export default {
    components: {
      //...
    },
    methods: {
      linkShow(){
          //...
      },
      linkHidden(){
          //...
      },
      linkCopy(){
        var clipboard = new Clipboard(".copy-invite-link");
        clipboard.on("success", function(e){
          console.log("success");
          console.log(e.text);       
        });
        clipboard.on("error", function(e){
          console.log("error");       
        });
        clipboard.destroy();
      },
      numCopy(){
        var clipboard = new Clipboard(".copy-invite-number");
        clipboard.on("success", function(e){
          console.log("success");
          console.log(e.text);       
        });
        clipboard.on("error", function(e){
          console.log("error");        
        });
        clipboard.destroy();
      },
    }
  }
##without `clipboard.destroy()`,it works fine
import Clipboard from 'clipboard';
  export default {
    components: {
      //...
    },
    methods: {
      linkShow(){
          //...
      },
      linkHidden(){
          //..
      },
      linkCopy(){
        var clipboard = new Clipboard(".copy-invite-link");
        clipboard.on("success", function(e){
          console.log("success");
          console.log(e.text);       
        });
        clipboard.on("error", function(e){
          console.log("error");       
        });
        //clipboard.destroy();
      },
      numCopy(){
        var clipboard = new Clipboard(".copy-invite-number");
        clipboard.on("success", function(e){
          console.log("success");
          console.log(e.text);       
        });
        clipboard.on("error", function(e){
          console.log("error");        
        });
        //clipboard.destroy();
      },
    }
  }
##official web page suggestions(https://clipboardjs.com/)
Also, if you are working with single page apps, you may want to manage the lifecycle of the DOM more precisely. Here's how you clean up the events and objects that we create.
Copy to clipboard
`var clipboard = new Clipboard('.btn');
clipboard.destroy();`

**Comment by zenorocha** [comment] 2017-11-19 19:46
Closing since it didn't include a minimal example on JSFiddle that reproduces the problem.

**Closed by zenorocha** 2017-11-19 19:46 UTC
