### ISSUE TITLE
doesn't work on iOS 12.2

### ISSUE THREAD

**Issue by lsc949982212** [zenorocha/clipboard.js#625] opened 2019-04-22 03:20 UTC
it can works on versions before iOS12.2 , but doesn't work on iOS12.2

**Comment by keepchen** [comment] 2019-04-22 03:33
> it can works on versions before iOS12.2 , but doesn't work on iOS12.2

+1

**Comment by wangcheng007** [comment] 2019-04-22 10:33
Did you use fastclick？

**Comment by keepchen** [comment] 2019-04-23 03:07
> Did you use fastclick？

Yes, I used it.
I found that the trigger for each `trigger` is `fastClickScrollParent`

**Comment by wangcheng007** [comment] 2019-04-23 03:28
> > Did you use fastclick？
> 
> Yes, I used it.
> I found that the trigger for each `trigger` is `fastClickScrollParent`

你可能需要改一下 fastclick 里面的方法 这篇[文章](https://www.cnblogs.com/vajoy/p/5522114.html) 上面有说，就是 ckipboard 和 fastclick 两个冲突了。

**Comment by keepchen** [comment] 2019-04-23 03:38
> > > Did you use fastclick？
> > 
> > 
> > Yes, I used it.
> > I found that the trigger for each `trigger` is `fastClickScrollParent`
> 
> 你可能需要改一下 fastclick 里面的方法 这篇[文章](https://www.cnblogs.com/vajoy/p/5522114.html) 上面有说，就是 ckipboard 和 fastclick 两个冲突了。

谢谢

**Comment by Burongtang** [comment] 2019-04-23 09:45
请问一下 ，如何改写

**Comment by adolt** [comment] 2019-04-28 07:42
> 请问一下 ，如何改写

可以单独 [禁用fastclick](https://github.com/ftlabs/fastclick#ignore-certain-elements-with-needsclick)

**Comment by Burongtang** [comment] 2019-05-06 02:27
> > 请问一下，如何改写
> 
> 单独可以[禁用fastclick](https://github.com/ftlabs/fastclick#ignore-certain-elements-with-needsclick)
不怎么明白 - -。

**Comment by sunshanguang** [comment] 2019-05-21 12:42
> 它可以在iOS12.2之前的版本上运行，但在iOS12.2上不起作用

解决了嘛 兄弟

**Comment by zenorocha** [comment] 2020-02-29 20:12
Closing since this is a behavior caused by fastclick and not this library.

**Closed by zenorocha** 2020-02-29 20:12 UTC
